### ISSUE TITLE
Unable to import snap

### ISSUE THREAD

**Issue by vaastav** [snap-stanford/snap-python#117]
I followed the installation instructions but I am unable to import snap. I get the following Import Error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "swig/snap.py", line 32, in <module>
    _snap = swig_import_helper()
  File "swig/snap.py", line 28, in swig_import_helper
    _mod = imp.load_module('_snap', fp, pathname, description)
  File "/home/vaastav/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/vaastav/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return **_load(spec)**
ImportError: swig/_snap.so: undefined symbol: PyInstance_Type

**Comment by billlyzhaoyh** [comment]
I am encountering a similar error here in my anaconda environment:

>>> import snap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/billyzhaoyh/anaconda/envs/aihack/lib/python3.7/site-packages/snap_stanford-5.0.0_dev_macosx10.14.6_x64_py3.7-py3.7.egg/snap.py", line 15, in <module>
    import _snap
ImportError: dlopen(/Users/billyzhaoyh/.local/lib/python3.7/site-packages/_snap.so, 2): Symbol not found: _PyBytes_AsString
  Referenced from: /Users/billyzhaoyh/.local/lib/python3.7/site-packages/_snap.so
  Expected in: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
 in /Users/billyzhaoyh/.local/lib/python3.7/site-packages/_snap.so

for some reason, the snap address is pointing to my python2.7 address
